name: flash_chat_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  modal_progress_hud: ^0.1.3
  image: ^3.2.0
  flutter_share: ^2.0.0
  extended_text_field: ^10.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  vrouter: ^1.2.1
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17
  permission_handler: ^9.2.0
  tuple: ^2.0.0
  intl: ^0.17.0
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/