name: flash_chat_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  # modal_progress_hud: ^0.1.3
  image: ^4.0.17
  flutter_share: ^2.0.0
  extended_text_field: ^12.0.1
  modal_progress_hud_nsn: ^0.3.0
  vrouter: ^1.2.1
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  permission_handler: ^10.4.3
  tuple: ^2.0.2
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.5
  camera: ^0.10.5+2
  path_provider: ^2.0.11
  path: ^1.8.1
  shared_preferences: ^2.0.15
  contacts_service: ^0.6.3
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/